# Setup

title:            		select64
baseurl: 				http://josephfusco.github.io/select64
collections:
 - icons

# Dependencies

markdown:         		redcarpet
highlighter:      		pygments

# SCSS

sass:
  sass_dir: _sass
  style: :compressed