# Setup

title:            		select64
baseurl: 				""

permalink:           	pretty
relative_permalinks: 	true

collections:
 - icons

# Dependencies

markdown:         		redcarpet
highlighter:      		pygments

# SCSS

sass:
  sass_dir: _sass
  style: :compressed