# Setup

title:            		select64
url: 					http://josephfusco.github.io/
baseurl: 				select64
collections:
 - icons

# Dependencies

markdown:         		redcarpet
highlighter:      		pygments

# SCSS

sass:
  sass_dir: _sass
  style: :compressed