# Setup

title:            		select64
port:    				4000
host:    				127.0.0.1
baseurl: 				""

permalink:           	pretty
relative_permalinks: 	true

collections:
 - icons

# Dependencies

markdown:         		redcarpet
highlighter:      		pygments

# SCSS

sass:
  sass_dir: _sass
  style: :compressed